### PR TITLE
Change all the things

### LINKED ISSUE #140: 2.2.5 Add Calendar Failed at First time
I use 2.2.5 on iOS. That can compile and execute on iPhone. 
If the app is new installed, the permission grant dialog will be showed up. When you grant it, the event page is showed up. Tap "Add", it appears "Error".

I roll back to 2.2.4, it works good at same scenario. 

However, looks like the 2.2.5 got something wrong when add the event in calendar after grant permission.

<Note> my iPhone 15 is installed with 16.7 iOS.

### PR DESCRIPTION
**Pull request by pikaju**
This PR is meant to improve the behavior of the add_2_calendar package.

Before this PR, the Future returned by the package sometimes didn't complete at all (not even with an error). Now, we get a result enum that indicates whether an appointment has been added, the process was canceled, or there was a permission error. This makes it possible to display a success snackbar when, for example, an appointment was added to the calendar.

I would also like to take the chance to fix https://github.com/ja2375/add_2_calendar/issues/140, as I know we had this issue ourselves. However, I am unsure if it still exists.

### CODE REVIEW

File: example/lib/main.dart [hunk 1]
```diff
@@ -43,39 +45,42 @@ class MyApp extends StatelessWidget {
             ListTile(
               title: const Text('Add normal event'),
               trailing: const Icon(Icons.calendar_today),
-              onTap: () {
-                Add2Calendar.addEvent2Cal(
+              onTap: () async {
+                final result = await Add2Calendar.addEvent2Cal(
                   buildEvent(),
                 );
+                print(result);
```
Comment (akvus) [inline example/lib/main.dart:52]: Should we remove these prints?

Comment (pikaju) [inline example/lib/main.dart:52]: I left them intentionally to illustrate the result-feature that didn't exist before

**Review by akvus — APPROVED** [review]
